version: "4.1.0.{build}"

init:
  - appveyor DownloadFile https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0-preview4/scripts/obtain/dotnet-install.ps1
  - ps: |
      & .\dotnet-install.ps1 -Channel "preview" -Version "1.0.0-preview4-004233"
      Remove-Item .\dotnet-install.ps1

before_build:

build_script: 
    - ps: |
        dotnet restore
        dotnet pack Cocotte\Cocotte.csproj -c Release -o ..\artifacts --version-suffix %APPVEYOR_BUILD_VERSION%-prerelease 
test: off

after_build:

artifacts:
  - path: 'artifacts\*.nupkg'

deploy: off

nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true